### ISSUE TITLE
Minimum training example for Qwen 1.5 72B

### ISSUE THREAD

**Issue by Peter-Devine** [alibaba/Pai-Megatron-Patch#147]
Hi, would you be able to share an example training script for Qwen 1.5 72B? Is it significantly different to Qwen 1?

Ideally, I'd like both a script for full fine-tuning and for LoRA/QLoRA.

Also, what are the minimum requirements for training a model of this size? I.e. how many A100/A800s would we need to fine-tune Qwen 1.5 72B?

I see that Qwen 1 72B requires 4 A100 as described in https://github.com/alibaba/Pai-Megatron-Patch/issues/95

Thanks and 谢谢!

**Comment by lwmlyy** [comment]
Hi, thanks for your interest.  

For Qwen1.5 performance, please refer to this [report
](https://arxiv.org/pdf/2309.16609.pdf).  


Please refer to [convert](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/toolkits/model_checkpoints_convertor/qwen/model_convertor.sh) for model converting and [train](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/examples/qwen1.5/run_finetune_megatron_qwen_withGA.sh) for model training.  

For finetuning Qwen-72b, you need 4 nodes of A100/A800-80G*8.

**Comment by Peter-Devine** [comment]
Hi @lwmlyy , thanks for the response.

Just in case anyone is interested, I was able to train Qwen 1.5 72B GPTQ 4bit with a LoRA adapter using this config with Axolotl using only 1 A100 (80GB) card.

```yaml
base_model: Qwen/Qwen1.5-72B-Chat-GPTQ-Int4
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
gptq: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: ABCDEFG.json
    ds_type: json # see other options below
    type: sharegpt
    conversation: chatml
dataset_prepared_path: /workspace/ABCDEFG
val_set_size: 0.0002
output_dir: /workspace/ABCDEFG

sequence_len: 6000 
sample_packing: true
pad_to_sequence_len:

adapter: lora
lora_model_dir:
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

use_wandb: true
wandb_project: ABCDEFG
wandb_entity: ABCDEFG
wandb_name: ABCDEFG

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.00005

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention:

warmup_steps: 10
evals_per_epoch: 40
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 40
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
```
